### PR TITLE
Type name aliases

### PR DESCRIPTION
**Pull request by XieX**
This PR makes a few changes.

## Fixes the leading space in operation descriptions

You'll see this in our generated spec:

```
        "description": " Get the status for a particular feature flag.",
```

Note the leading space in front of the description. This PR includes a fix to no longer add that leading space.

## Adds `--omit-packages` arg

The `@PackageAlias` tag can be used to omit a single package name, but if you want to omit all of them at once, this command line argument will do that for you. Note that it _does not_ check for conflicts, so for now you would need to be confident you're not going to have any (I had intended to throw if conflicting schema names exist, but turned out to be a bit more work than first I thought, can look into it as followup work if we have time).

## `@ApiSchemaName` annotation for types

Supports including a type annotation to rename the schema object, e.g. if I have a struct that I named poorly and would rather have it named something else in my generated spec, fear not!

```
// @ApiSchemaName Foo
type PoorlyNamedFooType struct {
```

### CODE REVIEW

**Comment by InTheCloudDan** [comment]
I 🤯 you got struct names aliases working!! Is an example of it in `example.json` and I'm missing it? If not can we add it there just as a basic check?

**Comment by XieX** [comment]
> Is an example of it in `example.json` and I'm missing it? If not can we add it there just as a basic check?

Good call! Added one 👍  🐦

**Review by InTheCloudDan — APPROVED** [review]
🚀

**Comment by jazanne** [comment]
this is great!

**Pull request merged**
